# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Basic stuff
# export Term="xterm-256color"
export HISTFILE=~/.config/zsh/.zsh_history

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

export PATH="/home/malthor/.local/bin:$PATH"
# Basic zsh settings
bindkey -v  # vi-mode
export KEYTIMEOUT=1
autoload -Uz compinit && compinit # need the next two lines for case insensitive tab completion
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'

## Colors
autoload -Uz colors && colors

setopt autocd
stty stop undef		# Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')

## beeping is annoying
unsetopt BEEP

# # Prompt Settings
declare -a PROMPTS
PROMPTS=(
    ""
    ""
    ""
    ""
    ""
    ""
)
RANDOM=$$$(date +%s)
ignition=${PROMPTS[$RANDOM % ${#RANDOM[*]}]}
PROMPT='%F{blue}%1~%f %F{cyan}$ignition%f '

## Git Settings
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
RPROMPT=\$vcs_info_msg_0_
zstyle ':vcs_info:git:*' formats '%F{yellow}(%b)%r%f'
zstyle ':vcs_info:*' enable git

## Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select

# FZF 
[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/malthor/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/malthor/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/malthor/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/malthor/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Aliases
alias pac='sudo pacman -S'
alias dot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

## Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

## confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

## get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

## aliases for frequently used cmds
alias ls='ls --color'
alias ll='ls -l --color'
alias la='ls -al --color'
alias less='less -R'
alias docker='sudo docker'
alias docker-compose='sudo docker-compose'
alias light='alacritty-colorscheme apply github-theme.yml'
alias dark='alacritty-colorscheme apply nightfly.yml'

alias config="cd ~/.config"
alias root='/'
alias vim='nvim'
alias vimo='nvim $(fzf)'
alias fd='fdfind'
alias copy='xsel -ib'
alias b='cd ..'
alias lsd='ls -d */'
alias youtube='youtube-dl -x --audio-format "mp3" --add-metadata'


